Repository ThanMatt/gamekeeper, pull requests merged in 2025-06, with the labels that each got.

#2 ci: Added netlify.toml and .node-version
  .node-version
  netlify.toml
  package.json
  pnpm-lock.yaml
Labels: ci/cd

#3 feat: Added vue game adapter
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/vue/VueGamePluginAdapter.vue
  src/content.config.ts
  src/lib/component-registry.ts
  src/pages/games/[slug]/[pluginSlug].astro
  src/vue.d.ts
Labels: enhancement

#5 Svelte Testing Library
  package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: chore

#7 ci: Updated netlify.toml
  .github/actions/setup-project/action.yml
  .github/workflows/ci.yml
  netlify.toml
Labels: ci/cd, chore

#10 docs: added CONTRIBUTING.md and pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation

#12 feat: Added @vite-pwa/astro to enable PWA capabilities
  .gitignore
  .husky/pre-commit
  astro.config.mjs
  eslint.config.js
  package.json
  pnpm-lock.yaml
  public/favicon.svg
  src/components/astro/Footer.astro
  src/components/astro/Head.astro
  src/layouts/Layout.astro
  src/swa.ts
  tsconfig.json
Labels: enhancement

#13 fix: netlify treat existing pages with trailing slashes as 404
  netlify.toml
Labels: bug
